# Generated by Django 3.0.5 on 2025-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
