# Generated by Django 3.0.5 on 2025-03-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_blooddonate_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='rejection_reason',
        ),
    ]
