# Generated by Django 3.0.5 on 2025-03-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
