# Generated by Django 3.0.5 on 2025-03-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='date',
            new_name='request_date',
        ),
    ]
