# Generated by Django 3.0.5 on 2025-03-20 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_auto_20250320_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['bloodgroup'], 'verbose_name': 'Blood Stock', 'verbose_name_plural': 'Blood Stocks'},
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='amount_per_unit',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.PositiveIntegerField(default=0, help_text='Number of units available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
