# Generated by Django 3.0.5 on 2025-03-20 19:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_auto_20250320_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
