# Generated by Django 3.0.5 on 2025-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_stock_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='cost_at_request',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at the time of request', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for the request', max_digits=10, null=True),
        ),
    ]
